- hosts: all
  name: Autoconverted job legacy-weirdo-integration-newton-puppet-scenario001 from
    old job gate-weirdo-integration-newton-puppet-scenario001
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - shell:
        cmd: |
          echo "[DEBUG]: JJB template name: {template-name}"

          # If this is called in a periodic job, these will not be set
          echo "Use default for ZUUL_BRANCH and ZUUL_REF if needed"
          export ZUUL_BRANCH=${ZUUL_BRANCH:-master}
          export ZUUL_REF=${ZUUL_REF:-None}

          # In the post pipeline ZUUL_REF is master but does not behave as we want
          # So fall back on None
          [ "$ZUUL_REF" = "master" ] && ZUUL_REF=None
          echo "Clean workspace"
          rm -Rf ./*

          echo "Clone $ZUUL_PROJECT"
          # zuul-cloner is installed as /usr/zuul-env/bin/zuul-cloner
          # in upstream images
          export PATH=$PATH:/usr/zuul-env/bin

          # Note (dmsimard): If we are running for a periodic job, there is no
          # incentive in using Zuul cloner because the jobs are not going to
          # potentially depend on things from the zuul context (ex: depends-on)
          # The zuul git namespace (where the job was triggered from) is also
          # wonky for periodic jobs. A periodic pipeline targetted at an
          # upstream project would still end up trying to clone from review.rdo.
          # This should be revisited in Zuul v3 which is supposedly not a
          # problem

          # We can receive reviews from review.openstack.org.
          # Builds that are run as third party for review.o.o are in the Zuul
          # pipelines prefixed by "openstack-".
          GIT_SOURCE="https://review.rdoproject.org/r"
          if [[ "${ZUUL_PIPELINE}" =~ "openstack-" ]]; then
              GIT_SOURCE="https://git.openstack.org"
          fi

          git config --global http.postBuffer 524288000
          git config --global https.postBuffer 524288000

          if [[ "${ZUUL_PIPELINE}" =~ "periodic" ]]; then
          # Note (trown): we need to make sure we clone this to the same
          # location as zuul-cloner will so that manual and periodic jobs
          # can share builders
              git clone --depth=1 $GIT_SOURCE/$ZUUL_PROJECT $ZUUL_PROJECT
          else
              zuul-cloner -v $GIT_SOURCE $ZUUL_PROJECT
          fi
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          CLONEMAP=$(mktemp)
          function cleanup {
              rm -f $CLONEMAP
          }
          trap cleanup EXIT
          cat > $CLONEMAP << EOF
          clonemap:
            - name: 'rdo-infra/weirdo'
              dest: 'weirdo'
            - name: 'rdo-infra/ansible-role-weirdo-(.*)'
              dest: 'weirdo/playbooks/roles/\1'
          EOF

          # Zuul clone WeIRDO and it's roles at their expected location
          zuul-cloner -m $CLONEMAP \
            https://review.rdoproject.org/r \
            rdo-infra/weirdo \
            rdo-infra/ansible-role-weirdo-common \
            rdo-infra/ansible-role-weirdo-logs \
            rdo-infra/ansible-role-weirdo-kolla \
            rdo-infra/ansible-role-weirdo-packstack \
            rdo-infra/ansible-role-weirdo-puppet-openstack
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'

    - shell:
        cmd: |
          # WeIRDO uses ARA for ansible-playbook run visualization
          export ARA_DATABASE="sqlite:///$WORKSPACE/ara-$JOB_NAME.sqlite"

          # Backwards compat for project and openstack_release
          # (dmsimard) TODO: Clean this up ASAP
          if [[ "puppet" == "puppet" ]]; then
              project="puppet-openstack"
          else
              project="puppet"
          fi

          if [[ "newton" != "master" ]]; then
              version="stable/newton"
          else
              version="newton"
          fi

          delorean_deps_url="https://trunk.rdoproject.org/centos7-newton/delorean-deps.repo"
          if [[ "false" == "true" ]]; then
              delorean_url="https://trunk.rdoproject.org/centos7-newton/current/delorean.repo"
          elif [[ "newton" == "master" ]]; then
              delorean_url="https://trunk.rdoproject.org/centos7-newton/puppet-passed-ci/delorean.repo"
          else
              delorean_url="https://trunk.rdoproject.org/centos7-newton/current-passed-ci/delorean.repo"
          fi

          cd weirdo
          # Prepare Ansible inventory to use localhost
          cat <<EOF >hosts
          localhost ansible_connection=local
          [openstack_nodes]
          localhost log_destination=/var/log/weirdo
          EOF

          tox -e ansible-playbook -- -vv -b -i hosts playbooks/$project-scenario001.yml \
              -e version=$version \
              -e openstack_release=newton \
              -e delorean_url=$delorean_url \
              -e delorean_deps_url=$delorean_deps_url \
              -e enable_puppet_modules_rpm=true
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
