---
- hosts: secondary-1, secondary-2
  tasks:
    - name: Populate repos
      ansible.builtin.shell: |
        rpm -q git || sudo yum -y install git
        sudo yum -y install python-setuptools python-requests python3-pip
        git clone https://github.com/openstack-k8s-operators/repo-setup
        pushd repo-setup
        sudo python3 setup.py install
        {% if openstack_release is defined %}
        sudo /usr/local/bin/repo-setup podified-ci-testing -b {{ openstack_release }}
        {% else %}
        sudo /usr/local/bin/repo-setup current-podified-dev
        {% endif %}
