---
- hosts: all
  name: Autoconverted job legacy-config-update from old job config-update
  tasks:

    - name: Ensure legacy workspace directory
      file:
        path: '{{ ansible_user_dir }}/workspace'
        state: directory

    - name: sf_configrepo_update
      shell:
        cmd: |
          set -e
          echo "[+] Updating configuration using $ZUUL_COMMIT"
          ssh root@install-server sf_configrepo_update $ZUUL_COMMIT
        chdir: '{{ ansible_user_dir }}/workspace'
      environment: '{{ zuul | zuul_legacy_vars }}'
